arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/generated
output-class: AppLocalizations
untranslated-messages-file: untranslated.txt
preferred-supported-locales: [ko, en, zh, es, ja, ru]
